# yaml-language-server: $schema=schema.json

version: 2

project_name: cockpit

builds:
  - id: cockpit-linux-amd64
    main: ./cmd/tui
    binary: cockpit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

  - id: cockpit-linux-arm64
    main: ./cmd/tui
    binary: cockpit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
